[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

[rpc_endpoints]
ethereum = "https://cloudflare-eth.com"
polygon = "https://polygon-rpc.com"
optimism = "https://opt-mainnet.g.alchemy.com/v2/CgU493K9wgZYqlbIGchQ_qP0gnN3YgSU"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
